import type { Locale } from "./i18n-shared";

export const trackCopy = {
  en: {
    title: "Visa tracking dashboard",
    subtitle: "Monitor expiry dates and policy changes for your digital nomad visas.",
    trialRemaining: "free tracks remaining",
    subscribeUnlock: "Subscribe for unlimited tracking →",
    subscribeNow: "Subscribe · $29/mo",
    addVisa: "+ Track a visa",
    addVisaTitle: "Add visa to track",
    selectVisa: "Select visa program",
    expiryDate: "Expiry date",
    addBtn: "Start tracking",
    adding: "Adding…",
    yourVisas: "Your tracked visas",
    demoNote: "Demo visas shown — add your own to start",
    expires: "Expires",
    daysLeft: "days left",
    policyChanges: "Recent policy changes (7 days)",
    viewPolicy: "View policy",
    paywallTitle: "Free trial used up",
    paywallBody: "You've used 5 free tracks. Subscribe for unlimited tracking and expiry alerts.",
    paywallCta: "Subscribe · $29/mo",
    statusOk: "On track",
    statusWarning: "Renew soon",
    statusUrgent: "Urgent",
    memberBadge: "✓ Member · unlimited tracking",
  },
  zh: {
    title: "签证追踪面板",
    subtitle: "监控数字游民签证到期日与政策变更。",
    trialRemaining: "次免费追踪剩余",
    subscribeUnlock: "订阅解锁无限追踪 →",
    subscribeNow: "订阅 · $29/月",
    addVisa: "+ 添加签证",
    addVisaTitle: "添加追踪签证",
    selectVisa: "选择签证项目",
    expiryDate: "到期日期",
    addBtn: "开始追踪",
    adding: "添加中…",
    yourVisas: "你追踪的签证",
    demoNote: "以下为演示签证 — 添加你自己的开始追踪",
    expires: "到期",
    daysLeft: "天剩余",
    policyChanges: "近期政策变更（7 天内）",
    viewPolicy: "查看政策",
    paywallTitle: "免费体验已用完",
    paywallBody: "你已使用 5 次免费追踪。订阅后可无限追踪并收到到期提醒。",
    paywallCta: "订阅 · $29/月",
    statusOk: "正常",
    statusWarning: "即将到期",
    statusUrgent: "紧急",
    memberBadge: "✓ 会员 · 无限追踪",
  },
} as const;

export function getTrackCopy(locale: Locale) {
  return trackCopy[locale];
}
