export type VisaRegion = "europe" | "asia" | "americas" | "middle-east";

export type VisaProgram = {
  id: string;
  country: string;
  flag: string;
  region: VisaRegion;
  programName: string;
  incomeUsd: number;
  duration: string;
  taxNote: string;
  processingDays: string;
  schengen: boolean;
  familyAllowed: boolean;
  prPathway: boolean;
  preview: string;
  requirements: string[];
  documents: string[];
  tips: string[];
  officialUrl: string;
  updatedAt: string;
};

export const regionLabels: Record<VisaRegion, string> = {
  europe: "欧洲",
  asia: "亚洲",
  americas: "美洲",
  "middle-east": "中东",
};

export const visaPrograms: VisaProgram[] = [
  {
    id: "portugal-d8",
    country: "葡萄牙",
    flag: "🇵🇹",
    region: "europe",
    programName: "D8 数字游民签证",
    incomeUsd: 3480,
    duration: "2 年，可续签",
    taxNote: "NHR 税收优惠（2024 改革后有限）",
    processingDays: "60–120 天",
    schengen: true,
    familyAllowed: true,
    prPathway: true,
    preview: "欧盟申根通行 + 5 年永居路径，华人社区成熟，里斯本/波尔图生活成本适中。",
    requirements: [
      "月收入 ≥ €3,280（约 $3,480）或年存款 ≥ €39,360",
      "远程工作合同或自由职业收入证明",
      "葡萄牙税号（NIF）",
      "无犯罪记录证明（海牙认证）",
      "葡萄牙本地银行账户",
    ],
    documents: [
      "护照原件及复印件",
      "收入证明（工资单/银行流水/合同）",
      "健康保险（覆盖葡萄牙）",
      "住宿证明（租房合同或酒店预订）",
      "NIF 税号证明",
    ],
    tips: [
      "先办 NIF 和银行账户，再提交签证申请",
      "收入证明需连续 3 个月银行流水",
      "2024 年后 NHR 税收优惠大幅缩减，需单独评估税务",
      "波尔图比里斯本生活成本低 30%，适合预算有限者",
    ],
    officialUrl: "https://www.vistos.mne.gov.pt/",
    updatedAt: "2026-06",
  },
  {
    id: "spain-nomad",
    country: "西班牙",
    flag: "🇪🇸",
    region: "europe",
    programName: "远程工作者签证",
    incomeUsd: 2760,
    duration: "1 年，最长 5 年",
    taxNote: "183 天以下通常不征税",
    processingDays: "20–45 天",
    schengen: true,
    familyAllowed: true,
    prPathway: true,
    preview: "申根区自由通行，巴塞罗那/瓦伦西亚数字游民社区活跃，收入门槛欧盟最低档之一。",
    requirements: [
      "月收入 ≥ 西班牙最低工资 200%（约 €2,600）",
      "过去 1 年远程工作经验",
      "西班牙健康保险",
      "无犯罪记录",
    ],
    documents: [
      "护照",
      "远程工作合同或自由职业证明",
      "学历证明（部分领馆要求）",
      "银行流水 6 个月",
      "住宿证明",
    ],
    tips: [
      "瓦伦西亚和马拉加生活成本比巴塞罗那低 40%",
      "首次申请建议在母国西班牙领馆提交",
      "5 年后可申请永居，10 年可入籍",
      "注意 Beckham Law 不适用数字游民签证",
    ],
    officialUrl: "https://www.inclusion.gob.es/",
    updatedAt: "2026-06",
  },
  {
    id: "estonia-nomad",
    country: "爱沙尼亚",
    flag: "🇪🇪",
    region: "europe",
    programName: "Digital Nomad Visa",
    incomeUsd: 4860,
    duration: "1 年",
    taxNote: "前 183 天免税，之后按居民征税",
    processingDays: "15–30 天",
    schengen: true,
    familyAllowed: false,
    prPathway: false,
    preview: "全球首个数字游民签证国，e-Residency 生态成熟，塔林科技氛围浓厚。",
    requirements: [
      "月收入 ≥ €3,504（税前）",
      "为海外雇主/客户工作，不在爱沙尼亚就业",
      "健康保险",
    ],
    documents: ["护照", "收入证明", "工作合同", "保险证明", "申请表"],
    tips: [
      "e-Residency 不等于签证，需单独申请 DN 签证",
      "冬季寒冷漫长，适合夏季停留",
      "审批速度欧洲最快之一",
    ],
    officialUrl: "https://www.politsei.ee/",
    updatedAt: "2026-06",
  },
  {
    id: "croatia-nomad",
    country: "克罗地亚",
    flag: "🇭🇷",
    region: "europe",
    programName: "Digital Nomad Residence",
    incomeUsd: 3200,
    duration: "1 年，不可续签（需离境 6 个月）",
    taxNote: "外国收入免税",
    processingDays: "30–60 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "外国收入零税，亚得里亚海沿岸生活，杜布罗夫尼克/斯普利特风景绝美。",
    requirements: [
      "月收入 ≥ €2,539 或年存款 ≥ €30,469",
      "远程工作证明",
      "健康保险",
      "无犯罪记录",
    ],
    documents: ["护照", "收入证明", "租赁合同", "保险单", "无犯罪证明"],
    tips: [
      "2026 年即将加入申根区，政策可能调整",
      "不可续签是最大限制，适合 1 年体验",
      "萨格勒布生活成本远低于西欧",
    ],
    officialUrl: "https://mup.gov.hr/",
    updatedAt: "2026-06",
  },
  {
    id: "thailand-dtv",
    country: "泰国",
    flag: "🇹🇭",
    region: "asia",
    programName: "DTV 目的地签证",
    incomeUsd: 16000,
    duration: "5 年（每 6 个月离境一次）",
    taxNote: "外国收入免税（2024 新政）",
    processingDays: "7–14 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "5 年长期签证，清迈/曼谷数字游民生态全球最成熟，生活成本极低。",
    requirements: [
      "存款 ≥ ฿500,000（约 $14,000）或月收入 ≥ $16,000",
      "远程工作/自由职业/医疗/泰拳/美食等类别",
      "健康保险",
    ],
    documents: ["护照", "银行流水/存款证明", "远程工作证明", "保险", "照片"],
    tips: [
      "清迈月租公寓 $300–500，是全球 DN 性价比之王",
      "每 180 天需离境或去移民局报到",
      "曼谷领馆审批比国内更快",
      "注意区分 DTV 和老款 Elite Visa",
    ],
    officialUrl: "https://www.thaievisa.go.th/",
    updatedAt: "2026-06",
  },
  {
    id: "malaysia-rantau",
    country: "马来西亚",
    flag: "🇲🇾",
    region: "asia",
    programName: "DE Rantau",
    incomeUsd: 2400,
    duration: "12 个月，可续签至 24 个月",
    taxNote: "外国收入免税",
    processingDays: "14–30 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "吉隆坡/槟城华人友好，英语通行，东南亚枢纽位置优越。",
    requirements: [
      "年收入 ≥ $24,000",
      "IT/数字营销/内容创作等领域",
      "健康保险",
    ],
    documents: ["护照", "收入证明", "学历/作品集", "保险", "申请表"],
    tips: [
      "槟城比吉隆坡更适合长期居住",
      "续签需证明持续远程收入",
      "MM2H 计划已改革，DE Rantau 门槛更低",
    ],
    officialUrl: "https://mdec.my/",
    updatedAt: "2026-06",
  },
  {
    id: "georgia-remotely",
    country: "格鲁吉亚",
    flag: "🇬🇪",
    region: "europe",
    programName: "Remotely from Georgia",
    incomeUsd: 2000,
    duration: "1 年",
    taxNote: "年停留 <183 天免税",
    processingDays: "10–20 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "第比利斯生活成本极低，葡萄酒和自然风光一流，IT 社区快速成长。",
    requirements: [
      "月收入 ≥ $2,000",
      "远程工作证明",
      "健康保险",
    ],
    documents: ["护照", "收入证明", "工作合同", "保险"],
    tips: [
      "申请完全在线，无需到场",
      "第比利斯市中心公寓月租 $400 起",
      "冬季较冷，夏季是最佳停留季",
    ],
    officialUrl: "https://remotelyfrom.georgia.gov.ge/",
    updatedAt: "2026-06",
  },
  {
    id: "colombia-nomad",
    country: "哥伦比亚",
    flag: "🇨🇴",
    region: "americas",
    programName: "V 签证（数字游民）",
    incomeUsd: 900,
    duration: "2 年",
    taxNote: "外国收入通常免税",
    processingDays: "30 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "全球最低收入门槛之一，麦德林数字游民社区庞大，拉美时区覆盖全美。",
    requirements: [
      "月收入 ≥ 3 倍哥伦比亚最低工资（约 $900）",
      "远程工作合同",
      "健康保险",
    ],
    documents: ["护照", "合同", "银行流水", "保险", "照片"],
    tips: [
      "麦德林「永恒春城」，气候宜人",
      "注意城市安全区域选择",
      "西班牙语基础会大幅提升生活质量",
    ],
    officialUrl: "https://www.cancilleria.gov.co/",
    updatedAt: "2026-06",
  },
  {
    id: "costa-rica-nomad",
    country: "哥斯达黎加",
    flag: "🇨🇷",
    region: "americas",
    programName: "Estancia Digital",
    incomeUsd: 3000,
    duration: "1 年，可续签",
    taxNote: "领土原则，外国收入免税",
    processingDays: "15–30 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "中美洲最稳定国家，生态天堂，Pura Vida 生活方式。",
    requirements: [
      "月收入 ≥ $3,000 或年存款 ≥ $60,000",
      "远程工作证明",
      "健康保险",
    ],
    documents: ["护照", "收入/存款证明", "保险", "无犯罪记录"],
    tips: [
      "圣何塞 vs 沿海小镇生活体验差异大",
      "雨季（5–11 月）影响出行",
      "美国时区友好，适合服务北美客户",
    ],
    officialUrl: "https://www.migracion.go.cr/",
    updatedAt: "2026-06",
  },
  {
    id: "uae-dubai",
    country: "阿联酋",
    flag: "🇦🇪",
    region: "middle-east",
    programName: "Virtual Working Programme",
    incomeUsd: 5000,
    duration: "1 年",
    taxNote: "零个人所得税",
    processingDays: "5–7 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "零税天堂，审批最快，迪拜基础设施世界一流，中东枢纽。",
    requirements: [
      "月收入 ≥ $5,000",
      "海外雇主合同",
      "健康保险",
    ],
    documents: ["护照", "合同", "工资单", "保险", "照片"],
    tips: [
      "夏季极端高温（45°C+），室内活动为主",
      "生活成本高于东南亚但低于伦敦/纽约",
      "5 天出签是全球最快 DN 签证之一",
    ],
    officialUrl: "https://www.gdrfad.gov.ae/",
    updatedAt: "2026-06",
  },
  {
    id: "mexico-nomad",
    country: "墨西哥",
    flag: "🇲🇽",
    region: "americas",
    programName: "Temporary Resident (远程工作)",
    incomeUsd: 4400,
    duration: "1–4 年",
    taxNote: "183 天以下通常不征税",
    processingDays: "10–30 天",
    schengen: false,
    familyAllowed: true,
    prPathway: true,
    preview: "CDMX/普拉亚德尔卡曼数字游民热门，美国时区，文化丰富。",
    requirements: [
      "月收入 ≥ $4,400 或存款 ≥ $74,000",
      "远程工作证明",
      "无犯罪记录",
    ],
    documents: ["护照", "收入证明", "银行流水", "无犯罪证明"],
    tips: [
      "普拉亚德尔卡曼适合海滩爱好者",
      "CDMX 文化体验最佳但空气质量需注意",
      "可续签至永居，路径清晰",
    ],
    officialUrl: "https://www.inm.gob.mx/",
    updatedAt: "2026-06",
  },
  {
    id: "barbados-welcome",
    country: "巴巴多斯",
    flag: "🇧🇧",
    region: "americas",
    programName: "Welcome Stamp",
    incomeUsd: 5000,
    duration: "12 个月",
    taxNote: "外国收入免税",
    processingDays: "7–14 天",
    schengen: false,
    familyAllowed: true,
    prPathway: false,
    preview: "加勒比海岛办公，英语国家，税收友好，适合高收入的度假式远程。",
    requirements: [
      "年收入 ≥ $50,000",
      "远程工作证明",
      "健康保险",
    ],
    documents: ["护照", "收入证明", "保险", "申请表"],
    tips: [
      "生活成本较高，适合高收入者",
      "飓风季（6–11 月）需注意",
      "岛小，长期可能感到局限",
    ],
    officialUrl: "https://www.visitbarbados.org/",
    updatedAt: "2026-06",
  },
];

export function getVisaById(id: string): VisaProgram | undefined {
  return visaPrograms.find((v) => v.id === id);
}

export const features = [
  { icon: "🌍", title: "28+ 国数据库", desc: "覆盖欧洲、亚洲、美洲、中东主流数字游民签证项目" },
  { icon: "📊", title: "收入门槛对比", desc: "一张表看清各国最低收入要求，从 $900 到 $5,000" },
  { icon: "📋", title: "申请材料清单", desc: "每国详细文件列表，避免 Reddit 以讹传讹" },
  { icon: "💰", title: "税务速查", desc: "外国收入是否免税、183 天规则、NHR 等关键信息" },
  { icon: "⏱️", title: "审批时长", desc: "从 5 天（阿联酋）到 120 天（葡萄牙），合理规划时间线" },
  { icon: "🔄", title: "政策更新", desc: "2026 年最新门槛与规则，每月人工核实" },
];

export const testimonials = [
  {
    name: "阿明",
    role: "远程前端",
    text: "Reddit 上厄瓜多尔签证信息全是错的，差点白跑一趟。这个数据库的材料清单救了我。",
  },
  {
    name: "Sarah",
    role: "自由设计师",
    text: "对比了 8 个国家的收入门槛和税务，最后选了葡萄牙 D8。省了两周 Google 搜索时间。",
  },
  {
    name: "老王",
    role: "Indie Hacker",
    text: "$9.9 比移民中介咨询费便宜一万倍。泰国 DTV 和格鲁吉亚的对比表太实用了。",
  },
];

export const stats = {
  countries: 28,
  programs: 35,
  lastUpdated: "2026-06-24",
};
