import type { Locale } from "./i18n-shared";

export type ProposalInput = {
  freelancerName: string;
  freelancerEmail: string;
  clientName: string;
  clientEmail: string;
  projectTitle: string;
  deliverables: string;
  timeline: string;
  amount: number;
  currency: string;
  paymentTerms: string;
  includeContract: boolean;
};

export type GeneratedProposal = {
  id: string;
  createdAt: string;
  validUntil: string;
  freelancer: { name: string; email: string };
  client: { name: string; email: string };
  project: {
    title: string;
    deliverables: string[];
    timeline: string;
    amount: number;
    currency: string;
    paymentTerms: string;
  };
  contractClauses: string[];
  invoice: {
    number: string;
    dueDate: string;
    lineItems: { description: string; amount: number }[];
    total: number;
    currency: string;
  };
  markdown: string;
};

const contractClausesByLocale = {
  en: [
    "Intellectual property: upon full payment, client receives full usage rights to final deliverables.",
    "Revisions: quote includes 2 reasonable revision rounds; extra scope billed at $80/hour.",
    "Cancellation: full refund before project start; after start, billed for completed work.",
    "Confidentiality: both parties keep project information confidential for 2 years.",
    "Disputes: friendly negotiation first; unresolved disputes go to arbitration.",
  ],
  zh: [
    "知识产权：项目交付并收到全款后，客户获得最终交付物的完整使用权。",
    "修改范围：报价包含 2 轮合理修改，超出范围按 $80/小时计费。",
    "取消政策：项目启动前取消全额退款；启动后取消按已完成工作量结算。",
    "保密条款：双方对项目相关信息保密，期限 2 年。",
    "争议解决：优先友好协商，协商不成提交仲裁。",
  ],
} as const;

export function generateProposal(
  input: ProposalInput,
  locale: Locale = "en"
): GeneratedProposal {
  const id = `PROP-${Date.now().toString(36).toUpperCase()}`;
  const now = new Date();
  const validUntil = new Date(now);
  validUntil.setDate(validUntil.getDate() + 14);

  const deliverablesList = input.deliverables
    .split("\n")
    .map((d) => d.trim())
    .filter(Boolean);

  const contractClauses = input.includeContract
    ? [...contractClausesByLocale[locale]]
    : [];

  const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;
  const dueDate = new Date(now);
  dueDate.setDate(dueDate.getDate() + 15);

  const lineItems = deliverablesList.map((d, i) => ({
    description: d,
    amount: i === 0 ? input.amount : 0,
  }));

  if (lineItems.length === 0) {
    lineItems.push({ description: input.projectTitle, amount: input.amount });
  } else {
    lineItems[0].amount = input.amount;
  }

  const currencySymbol =
    input.currency === "CNY" ? "¥" : input.currency === "EUR" ? "€" : "$";

  const dateLocale = locale === "zh" ? "zh-CN" : "en-US";
  const labels =
    locale === "zh"
      ? {
          title: "项目报价单",
          quoteId: "报价编号",
          date: "日期",
          validUntil: "有效期至",
          provider: "服务提供方",
          name: "姓名",
          email: "邮箱",
          client: "客户",
          company: "公司/姓名",
          overview: "项目概述",
          deliverables: "交付物",
          timeline: "项目周期",
          amount: "报价金额",
          payment: "付款条款",
          contract: "合同条款",
          invoice: "发票信息",
          invoiceNo: "发票号",
          due: "到期日",
          item: "项目",
          total: "合计",
          footer: "本报价由自由职业报价单生成 · 接受本报价即表示同意上述条款",
        }
      : {
          title: "Project Proposal",
          quoteId: "Quote ID",
          date: "Date",
          validUntil: "Valid until",
          provider: "Service provider",
          name: "Name",
          email: "Email",
          client: "Client",
          company: "Company / name",
          overview: "Project overview",
          deliverables: "Deliverables",
          timeline: "Timeline",
          amount: "Quote amount",
          payment: "Payment terms",
          contract: "Contract clauses",
          invoice: "Invoice",
          invoiceNo: "Invoice #",
          due: "Due date",
          item: "Item",
          total: "Total",
          footer: "Generated by Freelance Proposal · Accepting this quote agrees to the terms above",
        };

  const markdown = `# ${labels.title}

**${labels.quoteId}:** ${id}  
**${labels.date}:** ${now.toLocaleDateString(dateLocale)}  
**${labels.validUntil}:** ${validUntil.toLocaleDateString(dateLocale)}

---

## ${labels.provider}
- **${labels.name}:** ${input.freelancerName}
- **${labels.email}:** ${input.freelancerEmail}

## ${labels.client}
- **${labels.company}:** ${input.clientName}
- **${labels.email}:** ${input.clientEmail}

---

## ${labels.overview}
**${input.projectTitle}**

### ${labels.deliverables}
${deliverablesList.map((d) => `- ${d}`).join("\n")}

### ${labels.timeline}
${input.timeline}

### ${labels.amount}
**${currencySymbol}${input.amount.toLocaleString()} ${input.currency}**

### ${labels.payment}
${input.paymentTerms}

${
  contractClauses.length > 0
    ? `---

## ${labels.contract}

${contractClauses.map((c, i) => `${i + 1}. ${c}`).join("\n\n")}`
    : ""
}

---

## ${labels.invoice}

**${labels.invoiceNo}:** ${invoiceNumber}  
**${labels.due}:** ${dueDate.toLocaleDateString(dateLocale)}

| ${labels.item} | ${labels.amount} |
|------|------|
${lineItems.map((item) => `| ${item.description} | ${currencySymbol}${item.amount.toLocaleString()} |`).join("\n")}
| **${labels.total}** | **${currencySymbol}${input.amount.toLocaleString()}** |

---

*${labels.footer}*
`;

  return {
    id,
    createdAt: now.toISOString(),
    validUntil: validUntil.toISOString(),
    freelancer: { name: input.freelancerName, email: input.freelancerEmail },
    client: { name: input.clientName, email: input.clientEmail },
    project: {
      title: input.projectTitle,
      deliverables: deliverablesList,
      timeline: input.timeline,
      amount: input.amount,
      currency: input.currency,
      paymentTerms: input.paymentTerms,
    },
    contractClauses,
    invoice: {
      number: invoiceNumber,
      dueDate: dueDate.toISOString(),
      lineItems,
      total: input.amount,
      currency: input.currency,
    },
    markdown,
  };
}
